config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/registration", to: "accounts#new"
  get "/profile", to: "accounts#show"
  get "/changepassword", to: "accounts#edit"
  get "/login", to: "sessions#new"

  post "/registration", to: "accounts#create"
  post "/login", to: "sessions#create"

  patch "/changepassword", to: "accounts#update"

  delete "/logout", to: "sessions#destroy"

  resources :account_activations, only: %i(edit)
  resources :password_resets, except: %i(show index destroy)

  resources :locations, only: %i(index show) do
    resources :reviews, only: %i(create destroy)
    resources :rooms, only: :show
  end

  resources :reservations, only: %i(new create)

  namespace :admin do
    resources(:users){get "search", on: :collection}
    resources(:location_types){get "search", on: :collection}
    resources(:services, except: :destroy){get "search", on: :collection}
    resources(:bed_details, except: :destroy){get "search", on: :collection}
    resources(:locations, only: %i(index show update)){get "search", on: :collection}

    root "static_pages#home"
  end

  namespace :manager do
    root "static_pages#home"
    resources :locations, except: :index do
      get "search", on: :collection
      resources :reviews, only: [:show]
      resources(:rooms, except: :destroy){get "search", on: :collection}
    end
  end
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :rooms_services, dependent: :destroy
  has_many :rooms, through: :rooms_services

  validates :name, presence: true, uniqueness: true, length: {maximum: Settings.validates.service.maximum_name}

  scope :option_list, ->{select :id, :name}
end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < Admin::ApplicationController
  before_action :load_service, except: %i(new index create search)

  def index
    @services = Service.order(:name)
      .page(params[:page]).per Settings.controllers.admin.services.pag
  end

  def search
    @services = SearchService.new(Service,
      search_params, Settings.search_fields.service).all_records
      .page(params[:page]).per Settings.controllers.admin.services.pag
    render :index
  end

  def show; end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new service_params
    if @service.save
      flash[:success] = t ".create_success"
      redirect_to request.referer
    else
      render :new
    end
  end

  def edit; end

  def update
    if @service.update service_params
      flash[:success] = t ".update_success"
      redirect_to request.referer
    else
      render :edit
    end
  end

  private
  def service_params
    params.require(:service).permit :name
  end

  def search_params
    params.slice :content, :field
  end

  def load_service
    @service = Service.find_by id: params[:id]
    return if @service
    redirect_to admin_services_url
  end
end

app/views/admin/services/_form.html.erb
<%= form_for [:admin, @service] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <div class="form-group">
    <%= f.label :name, t(".form_name") %>
    <%= f.text_field :name, class: "form-control", placeholder: t(".form_name") %>
  </div>

  <%= f.button yield(:button_text), class: "btn btn-success mr-2" %>
  <%= link_to t(".form_cancel"), admin_services_path, class: "btn btn-light" %>
<% end %>

app/views/admin/services/_modal.html.erb
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel"><%= t ".confirm" %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <%= link_to t(".del"), admin_service_path(@service), method: :delete, class: "btn btn-danger" %>
        <button type="button" class="btn btn-light" data-dismiss="modal"><%= t ".cancel" %></button>
      </div>
    </div>
  </div>
</div>

app/views/admin/services/_service.html.erb
<tr>
  <td><%= link_to service.name, admin_service_path(service) %></td>
  <td><%= l service.created_at, format: :full %></td>
  <td><%= l service.updated_at, format: :full %></td>
</tr>

app/views/admin/services/index.html.erb
<%= provide :title, t(".page_title") %>

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title"><%= t ".page_title" %></h4>
        <%= render "shared/search", path: search_admin_services_path, fields: Settings.search_fields.service %>
        <table class="table">
          <thead>
            <tr>
              <th><%= t ".name" %></th>
              <th><%= t ".create_at" %></th>
              <th><%= t ".update_at" %></th>
            </tr>
          </thead>
          <tbody>
            <%= render @services %>
          </tbody>
        </table>
        <%= paginate @services %>
      </div>
    </div>
  </div>
</div>

app/views/admin/services/show.html.erb
<%= provide :title, @service.name %>

<div class="row">
  <div class="col-12 card">
    <div class="card-body">
      <address>
        <p class="font-weight-bold"><%= @service.name %>
        <p><%= t ".created_at" %>: <%= l @service.created_at, format: :full %></p>
        <p><%= t ".updated_at" %>: <%= l @service.updated_at, format: :full %></p>
      </address>
      <%= link_to t(".edit_but"), edit_admin_service_path(@service), class: "btn btn-primary btn-sm float-right" %>
    </div>
  </div>
</div>