config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/registration", to: "accounts#new"
  get "/profile", to: "accounts#show"
  get "/changepassword", to: "accounts#edit"
  get "/login", to: "sessions#new"

  post "/registration", to: "accounts#create"
  post "/login", to: "sessions#create"

  patch "/changepassword", to: "accounts#update"

  delete "/logout", to: "sessions#destroy"

  resources :account_activations, only: %i(edit)
  resources :password_resets, except: %i(show index destroy)

  resources :locations, only: %i(index show) do
    resources :reviews, only: %i(create destroy)
    resources :rooms, only: :show
  end

  resources :reservations, only: %i(new create)

  namespace :admin do
    resources(:users){get "search", on: :collection}
    resources(:location_types){get "search", on: :collection}
    resources(:services, except: :destroy){get "search", on: :collection}
    resources(:bed_details, except: :destroy){get "search", on: :collection}
    resources(:locations, only: %i(index show update)){get "search", on: :collection}

    root "static_pages#home"
  end

  namespace :manager do
    root "static_pages#home"
    resources :locations, except: :index do
      get "search", on: :collection
      resources :reviews, only: [:show]
      resources(:rooms, except: :destroy){get "search", on: :collection}
    end
  end
end

app/views/layouts/admin/_footer.html.erb
<footer class="footer">
  <div class="container-fluid clearfix">
    <span class="text-muted d-block text-center text-sm-left d-sm-inline-block"><%= t ".copyright" %>
      <%= link_to t(".link"), root_path, target: "_blank" %>. All rights reserved.</span>
    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"><%= t ".slogan" %>
      <i class="mdi mdi-heart text-danger"></i>
    </span>
  </div>
</footer>

app/views/layouts/admin/_js.html.erb
<%= javascript_include_tag "admin/application", "data-turbolinks-track": "reload" %>

app/views/layouts/admin/_meta.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

app/views/layouts/admin/_nav.html.erb
<nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
  <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center">
    <%= link_to admin_root_path, class: "navbar-brand brand-logo" do %>
      <%= image_tag "admin/logo.png", alt: "logo" %>
    <% end %>
    <%= link_to admin_root_path, class: "navbar-brand brand-logo-mini" do %>
      <%= image_tag "admin/logo-mini.svg", alt: "logo" %>
    <% end %>
  </div>
  <div class="navbar-menu-wrapper d-flex align-items-center">
    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
      <span class="mdi mdi-menu"></span>
    </button>
    <ul class="navbar-nav navbar-nav-right">
      <li class="nav-item dropdown ml-4">
        <%= link_to nil, class: "nav-link count-indicator dropdown-toggle", id: "notificationDropdown", data: {toggle: "dropdown"} do %>
          <i class="mdi mdi-bell-outline"></i>
          <span class="count bg-success">4</span>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list pb-0" aria-labelledby="notificationDropdown">
          <%= link_to "#", class: "dropdown-item py-3 border-bottom" do %>
            <p class="mb-0 font-weight-medium float-left"><%= t ".notification" %> </p>
            <span class="badge badge-pill badge-primary float-right"><%= t ".view_all" %>
              </span>
          <% end %>
          <%= link_to "#", class: "dropdown-item preview-item py-3" do %>
            <div class="preview-thumbnail">
              <i class="mdi mdi-airballoon m-auto text-primary"></i>
            </div>
            <div class="preview-item-content">
              <h6 class="preview-subject font-weight-normal text-dark mb-1"><%= t ".new_user" %></h6>
              <p class="font-weight-light small-text mb-0"> <%#= time %> </p>
            </div>
          <% end %>
          <%= link_to "#", class: "dropdown-item preview-item py-3" do %>
            <div class="preview-thumbnail">
              <i class="mdi mdi-airballoon m-auto text-primary"></i>
            </div>
            <div class="preview-item-content">
              <h6 class="preview-subject font-weight-normal text-dark mb-1"><%= t ".new_location" %></h6>
              <p class="font-weight-light small-text mb-0"> <%#= time %> </p>
            </div>
          <% end %>
        </div>
      </li>
      <li class="nav-item dropdown d-none d-xl-inline-block">
        <%= link_to nil, class: "nav-link dropdown-toggle", id: "UserDropdown", data: {toggle: "dropdown"}, aria: {expanded: "false"} do %>
          <span class="profile-text"><%#= current admin %></span>
          <%= image_tag "admin/faces/face8.jpg", alt: "Profile image", class: "img-xs rounded-circle" %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
          <%= link_to nil, class: "dropdown-item p-0" do %>
            <div class="d-flex border-bottom">
              <div class="py-3 px-4 d-flex align-items-center justify-content-center">
                <i class="mdi mdi-bookmark-plus-outline mr-0 text-gray"></i>
              </div>
              <div class="py-3 px-4 d-flex align-items-center justify-content-center border-left border-right">
                <i class="mdi mdi-account-outline mr-0 text-gray"></i>
              </div>
              <div class="py-3 px-4 d-flex align-items-center justify-content-center">
                <i class="mdi mdi-alarm-check mr-0 text-gray"></i>
              </div>
            </div>
          <% end %>
          <%= link_to "Manage Accounts", "#", class: "dropdown-item mt-2" %>
          <%= link_to "Change Password", "#", class: "dropdown-item" %>
          <%= link_to "Sign Out", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
      <span class="icon-menu"></span>
    </button>
  </div>
</nav>

app/views/layouts/admin/_sidebar.html.erb
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">
    <li class="nav-item nav-profile">
      <div class="nav-link">
        <div class="user-wrapper">
          <div class="profile-image">
            <%= image_tag "admin/faces/face8.jpg", alt: "profile image" %> </div>
          <div class="text-wrapper">
            <p class="profile-name"><%#= current admin %></p>
            <div>
              <small class="designation text-muted"><%#= current user role %></small>
            </div>
          </div>
        </div>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#accounts" aria-expanded="true" aria-controls="accounts">
        <i class="menu-icon mdi mdi-account-multiple"></i>
        <span class="menu-title"><%= t ".accounts" %></span>
        <i class="menu-arrow"></i>
      </a>
      <div class="collapse" id="accounts">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <%= link_to t(".list_accounts"), admin_users_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t(".new_account"), new_admin_user_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </li>
    <li class="nav-item">
      <%= link_to  admin_locations_path, class: "nav-link" do %>
        <i class="menu-icon mdi mdi-city"></i>
        <span class="menu-title"><%= t ".locations" %></span>
      <% end %>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#location_types" aria-expanded="false" aria-controls="location_types">
        <i class="menu-icon mdi mdi-message-image"></i>
        <span class="menu-title"><%= t ".location_types" %></span>
        <i class="menu-arrow"></i>
      </a>
      <div class="collapse" id="location_types">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <%= link_to t(".list_location_types"), admin_location_types_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t(".new_location_type"), new_admin_location_type_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#services" aria-expanded="false" aria-controls="services">
        <i class="menu-icon mdi mdi-wifi"></i>
        <span class="menu-title"><%= t ".services" %></span>
        <i class="menu-arrow"></i>
      </a>
      <div class="collapse" id="services">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <%= link_to t(".list_services"), admin_services_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t(".new_service"), new_admin_service_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#bed_details" aria-expanded="false" aria-controls="bed_details">
        <i class="menu-icon mdi mdi-hotel"></i>
        <span class="menu-title"><%= t ".bed_details" %></span>
        <i class="menu-arrow"></i>
      </a>
      <div class="collapse" id="bed_details">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item">
            <%= link_to t(".list_bed_detail"), admin_bed_details_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t(".new_bed_detail"), new_admin_bed_detail_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </li>
  </ul>
</nav>

app/views/layouts/admin/_style.html.erb
<%= stylesheet_link_tag    "admin/application", media: "all", "data-turbolinks-track": "reload" %>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "layouts/admin/meta" %>
    <title><%= full_title yield(:title) %></title>
    <%= render "layouts/admin/style" %>
  </head>

  <body>
    <div class="container-scroller">
      <%= render "layouts/admin/nav" %>
      <div class="container-fluid page-body-wrapper">
        <%= render "layouts/admin/sidebar" %>
        <div class="main-panel">
          <div class="content-wrapper">
            <% flash.each do |message_type, message| %>
              <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
            <%= yield %>
          </div>
          <%= render "layouts/admin/footer" %>
        </div>
      </div>
    </div>
    <%= render "layouts/admin/js" %>
  </body>
</html>