config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/registration", to: "accounts#new"
  get "/profile", to: "accounts#show"
  get "/changepassword", to: "accounts#edit"
  get "/login", to: "sessions#new"

  post "/registration", to: "accounts#create"
  post "/login", to: "sessions#create"

  patch "/changepassword", to: "accounts#update"

  delete "/logout", to: "sessions#destroy"

  resources :account_activations, only: %i(edit)
  resources :password_resets, except: %i(show index destroy)

  resources :locations, only: %i(index show) do
    resources :reviews, only: %i(create destroy)
    resources :rooms, only: :show
  end

  resources :reservations, only: %i(new create)

  namespace :admin do
    resources(:users){get "search", on: :collection}
    resources(:location_types){get "search", on: :collection}
    resources(:services, except: :destroy){get "search", on: :collection}
    resources(:bed_details, except: :destroy){get "search", on: :collection}
    resources(:locations, only: %i(index show update)){get "search", on: :collection}

    root "static_pages#home"
  end

  namespace :manager do
    root "static_pages#home"
    resources :locations, except: :index do
      get "search", on: :collection
      resources :reviews, only: [:show]
      resources(:rooms, except: :destroy){get "search", on: :collection}
    end
  end
end

app/models/bed_detail.rb
class BedDetail < ApplicationRecord
  has_many :rooms

  scope :option_list, ->{select :id, :name}
end

app/controllers/admin/bed_details_controller.rb
class Admin::BedDetailsController < Admin::ApplicationController
  before_action :load_bed_detail, except: %i(new index create search)

  def index
    @bed_details = BedDetail.order(:name)
      .page(params[:page]).per Settings.controllers.admin.bed_details.pag
  end

  def search
    @bed_details = SearchService.new(BedDetail,
      search_params, Settings.search_fields.bed_detail).all_records
      .page(params[:page]).per Settings.controllers.admin.bed_details.pag
    render :index
  end

  def show; end

  def new
    @bed_detail = BedDetail.new
  end

  def create
    @bed_detail = BedDetail.new bed_detail_params
    if @bed_detail.save
      flash[:success] = t ".create_success"
      redirect_to request.referer
    else
      render :new
    end
  end

  def edit; end

  def update
    if @bed_detail.update bed_detail_params
      flash[:success] = t ".update_success"
      redirect_to request.referer
    else
      render :edit
    end
  end

  private
  def bed_detail_params
    params.require(:bed_detail).permit :name
  end

  def search_params
    params.slice :content, :field
  end

  def load_bed_detail
    @bed_detail = BedDetail.find_by id: params[:id]
    return if @bed_detail
    redirect_to admin_bed_details_url
  end
end

app/views/admin/bed_details/_bed_detail.html.erb
<tr>
  <td><%= link_to bed_detail.name, admin_bed_detail_path(bed_detail) %></td>
  <td><%= l bed_detail.created_at, format: :full %></td>
  <td><%= l bed_detail.updated_at, format: :full %></td>
</tr>

app/views/admin/bed_details/_form.html.erb
<%= form_for [:admin, @bed_detail] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <div class="form-group">
    <%= f.label :name, t(".form_name") %>
    <%= f.text_field :name, class: "form-control", placeholder: t(".form_name") %>
  </div>

  <%= f.button yield(:button_text), class: "btn btn-success mr-2" %>
  <%= link_to t(".form_cancel"), admin_bed_details_path, class: "btn btn-light" %>
<% end %>

app/views/admin/bed_details/edit.html.erb
<%= provide :title, t(".page_title") %>
<%= provide :button_text, t(".form_submit") %>

<div class="row flex-grow">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title"><%= t ".page_title" %></h4>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/bed_details/index.html.erb
<%= provide :title, t(".page_title") %>

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title"><%= t ".page_title" %></h4>
        <%= render "shared/search", path: search_admin_bed_details_path, fields: Settings.search_fields.bed_detail %>
        <table class="table">
          <thead>
            <tr>
              <th><%= t ".name" %></th>
              <th><%= t ".create_at" %></th>
              <th><%= t ".update_at" %></th>
            </tr>
          </thead>
          <tbody>
            <%= render @bed_details %>
          </tbody>
        </table>
        <%= paginate @bed_details %>
      </div>
    </div>
  </div>
</div>

app/views/admin/bed_details/new.html.erb
<%= provide :title, t(".page_title") %>
<%= provide :button_text, t(".form_submit") %>

<div class="row flex-grow">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title"><%= t ".page_title" %></h4>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/bed_details/show.html.erb
<%= provide :title, @bed_detail.name %>

<div class="row">
  <div class="col-12 card">
    <div class="card-body">
      <address>
        <p class="font-weight-bold"><%= @bed_detail.name %>
        <p><%= t ".created_at" %>: <%= l @bed_detail.created_at, format: :full %></p>
        <p><%= t ".updated_at" %>: <%= l @bed_detail.updated_at, format: :full %></p>
      </address>
      <%= link_to t(".edit_but"), edit_admin_bed_detail_path(@bed_detail), class: "btn btn-primary btn-sm float-right" %>
    </div>
  </div>
</div>