config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/registration", to: "accounts#new"
  get "/profile", to: "accounts#show"
  get "/changepassword", to: "accounts#edit"
  get "/login", to: "sessions#new"

  post "/registration", to: "accounts#create"
  post "/login", to: "sessions#create"

  patch "/changepassword", to: "accounts#update"

  delete "/logout", to: "sessions#destroy"

  resources :account_activations, only: %i(edit)
  resources :password_resets, except: %i(show index destroy)

  resources :locations, only: %i(index show) do
    resources :reviews, only: %i(create destroy)
    resources :rooms, only: :show
  end

  resources :reservations, only: %i(new create)

  namespace :admin do
    resources(:users){get "search", on: :collection}
    resources(:location_types){get "search", on: :collection}
    resources(:services, except: :destroy){get "search", on: :collection}
    resources(:bed_details, except: :destroy){get "search", on: :collection}
    resources(:locations, only: %i(index show update)){get "search", on: :collection}

    root "static_pages#home"
  end

  namespace :manager do
    root "static_pages#home"
    resources :locations, except: :index do
      get "search", on: :collection
      resources :reviews, only: [:show]
      resources(:rooms, except: :destroy){get "search", on: :collection}
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  include RoomDecorator

  has_many :rooms_services, dependent: :destroy
  has_many :services, through: :rooms_services
  has_many :images, as: :imageable, dependent: :destroy
  has_many :reservation_details
  has_many :reservations, through: :reservation_details
  belongs_to :location
  belongs_to :bed_detail
  accepts_nested_attributes_for :rooms_services

  mount_uploaders :pictures, PictureUploader

  validates_presence_of :name, :occupancy_limit, :living_room, :bed_room,
    :bath_room, :number_of_bed, :quantity


  ROOM_PARAMS = [:location, :name, :occupancy_limit, :living_room, :bed_room,
    :bath_room, :number_of_bed, :quantity, :price, :location_id, :bed_detail_id,
    :created_at, :updated_at, pictures: [], services: []].freeze

  scope :by_location_id, -> (location_id){ where("location_id = ?", location_id) }
  scope :list, (lambda do
    select :id, :name, :occupancy_limit, :quantity, :price, :created_at,
      :updated_at, :status
  end)
end

app/controllers/manager/application_controller.rb
module Manager
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper

    before_action :logged_in_user

    private
    def logged_in_user
      return if logged_in?
      store_location
      flash[:danger] = t "controllers.users.login_check"
      redirect_to login_url
    end
  end
end

app/controllers/manager/locations_controller.rb
class Manager::LocationsController < Manager::ApplicationController
  before_action :load_location, only: %i(show edit update)

  def show; end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new location_params.merge user_id: current_user.id
    if @location.save
      flash[:success] = t(".created")
      redirect_to manager_root_path
    else
      flash[:error] = t(".create_unsuccess")
      render :new
    end
  end

  def edit; end

  def update
    if @location.update location_params
      flash[:success] = t(".location_updated")
      redirect_to manager_location_path
    else
      render :edit
    end
  end

  private

  def location_params
    params.require(:location).permit Location::LOCATION_PARAMS
  end

  def search_params
    params.slice :content, :field
  end

  def load_location
    @location = Location.find_by id: params[:id]
    return if @location
    flash[:error] = t(".location_not_found")
    redirect_to manager_root_path
  end
end

app/controllers/manager/rooms_controller.rb
class Manager::RoomsController < Manager::ApplicationController
  before_action :load_location
  before_action :load_room, except: %i(new index create search)

  def index
    @rooms = @location.rooms.list.page(params[:page]).per Settings.page
  end

  def show; end

  def search
    @rooms = SearchService.new(@location.rooms,search_params,Settings.search_fields.room).all_records
      .page(params[:page]).per Settings.page
    render :index
  end

  def new
    @room = @location.rooms.new
  end

  def create
    @room = @location.rooms.new room_params.except(:services)
    @room.services << Service.find(filter_blank_attributes room_params[:services])
    if @room.save
      flash[:success] = t(".created")
      redirect_to manager_location_rooms_path
    else
      flash[:error] = t(".create_unsuccess")
      render :new
    end
  end

  def edit; end

  def update
    if @room.update room_params
      flash[:success] = t(".room_updated")
      redirect_to manager_location_rooms_path
    else
      render :edit
    end
  end

  private

  def room_params
    params.require(:room).permit Room::ROOM_PARAMS
  end

  def search_params
    params.slice :content, :field
  end

  def load_location
    @location = Location.find_by id: params[:location_id]
    return if @location
    flash[:error] = t(".location_not_found")
    redirect_to manager_locations_path
  end

  def load_room
    @room = @location.rooms.find_by id: params[:id]
    return if @room
    flash[:error] = t(".room_not_found")
    redirect_to manager_location_rooms_path
  end

  def filter_blank_attributes array
    array.reject { |e| e.to_s.empty? }
  end
end

app/controllers/manager/static_pages_controller.rb
module Manager
  class StaticPagesController < Manager::ApplicationController
    def home
      @locations= Location.includes(:location_type).page(params[:page]).per Settings.page
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :load_room, only: %i(show)

  def index
    @rooms= Room.all.page(params[:page]).per Settings.page
  end

  def show; end

  private

  def room_params
    params.require(:room).permit(:name, :occupancy_limit)
  end

  def load_location
    @location =Location.find_by id: params[:location_id]
  end

  def load_room
    @room = Room.find_by id: params[:id]
    return if @room
    flash[:error] = t(".room_not_found")
    redirect_to rooms_path
  end
end

app/helpers/manager/static_pages_helper.rb
module Manager::StaticPagesHelper
end

app/views/manager/rooms/_form.html.erb
<%= form_for [:manager, @location, @room] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <div class="form-group">
    <%= f.label :name, t(".name") %>
    <%= f.text_field :name, class: "form-control", placeholder: t(".enter_name") %>
  </div>
  <div class="form-group">
    <%= f.label :occupancy_limit, t(".form_occupancy_limit")%>
    <%= f.text_field :occupancy_limit, class: "form-control", placeholder: t(".enter_occupancy_limit") %>
  </div>
  <div class="form-group">
    <%= f.label :living_room, t(".form_living_room")%>
    <%= f.text_field :living_room, class: "form-control", placeholder: t(".enter_living_room") %>
  </div>
  <div class="form-group">
    <%= f.label :bed_room, t(".form_bed_room")%>
    <%= f.text_field :bed_room, class: "form-control", placeholder: t(".enter_bed_room") %>
  </div>
  <div class="form-group">
    <%= f.label :bath_room, t(".form_bath_room") %>
    <%= f.text_field :bath_room, class: "form-control", placeholder: t(".enter_bath_room") %>
  </div>
  <div class="form-group">
    <%= f.label :number_of_bed, t(".form_number_of_bed") %>
    <%= f.text_field :number_of_bed, class: "form-control", placeholder: t(".enter_number_of_bed") %>
  </div>
  <div class="form-group">
    <%= f.label :quantity, t(".form_quantity") %>
    <%= f.text_field :quantity, class: "form-control", placeholder: t(".enter_quantity") %>
  </div>
  <div class="form-group">
    <%= f.label :price, t(".form_price") %>
    <%= f.text_field :price, class: "form-control", placeholder: t(".enter_price") %>
  </div>
  <div class="form-group">
    <%= f.label :bed_detail, t(".form_bed_detail") %>
    <%= f.select :bed_detail_id, @room.bed_detail_option, { include_blank: false }, class: "js-example-basic-single", style: "width:100%" %>
  </div>
  <div class="form-group">
    <%= f.label :service, t(".form_services") %>
    <%= select "room", "services", @room.service_option, { include_blank: true }, class: "js-example-basic-multiple", multiple: "multiple", style: "width:100%" %>
  <div class="form-group">
    <%= f.label :pictures %>
    <%= f.file_field :pictures, multiple: true, accept: "image/jpeg, image/jpg, image/gif, image/png",  class: "file-upload-default" %>
    <div class="input-group col-xs-12">
      <input type="text" class="form-control file-upload-info" disabled placeholder="Upload Image">
      <span class="input-group-append">
        <button class="file-upload-browse btn btn-info" type="button">Upload</button>
      </span>
    </div>
  </div>
  <%= f.button yield(:button_text), class: "btn btn-success mr-2" %>
  <%= link_to t(".form_cancel"), request.referer, class: "btn btn-light" %>
<% end %>

app/views/manager/rooms/_room.html.erb
<tr>
  <td><%= link_to room.name, manager_location_room_path(@location, room) %></td>
  <td><%= room.occupancy_limit %></td>
  <td><%= room.quantity %></td>
  <td><%= room.price %></td>
  <td><%= label_tag nil, room.status_tag[:name], class: room.status_tag[:class] %></td>
  <td><%= l room.created_at, format: :full %></td>
  <td><%= l room.updated_at, format: :full %></td>
</tr>

app/views/manager/rooms/edit.html.erb
<%= provide :title, t(".edit_room") %>
<%= provide :button_text, t(".submit") %>

<div class="row flex-grow">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title"><%= t ".add_new_room" %></h4>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/manager/rooms/index.html.erb
<%= provide :title, t(".rooms") %>

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title"><%= t ".rooms" %></h4>
        <%= render "shared/search", path: search_manager_location_rooms_path, fields: Settings.search_fields.room %>
        <table class="table">
          <thead>
            <tr>
              <th><%= t ".room_name" %></th>
              <th><%= t ".occupancy_limit" %></th>
              <th><%= t ".quantity" %></th>
              <th><%= t ".price" %></th>
              <th><%= t ".status" %></th>
              <th><%= t ".created_at" %></th>
              <th><%= t ".update_at" %></th>
            </tr>
          </thead>
          <tbody>
            <%= render @rooms %>
          </tbody>
        </table>
        <%= paginate @rooms %>
      </div>
    </div>
  </div>
</div>

app/views/manager/rooms/new.html.erb
<%= provide :title, t(".add_new_room") %>
<%= provide :button_text, t(".submit") %>

<div class="row flex-grow">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title"><%= t ".add_new_room" %></h4>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/manager/rooms/show.html.erb
<%= provide :title, @room.name %>

<div class="row">
  <div class="col-12 card">
    <div class="card-body">
      <address>
        <p class="font-weight-bold"><%= @room.name %></p>
          <i class="mdi mdi-account-multiple"></i> <%= @room.occupancy_limit %>
          <i class="mdi mdi-account-multiple"></i> <%= @room.price %>
          <% @room.pictures.each do |picture| %>
            <div class="picture_medium">
              <%= image_tag(picture.url, class: "full_picture_auto")%>
            </div>
          <% end %>

        <p><%= t ".created_at" %>: <%= l @room.created_at, format: :full %></p>
        <p><%= t ".updated_at" %>: <%= l @room.updated_at, format: :full %></p>
      </address>
      <%= link_to t(".edit_but"), edit_manager_location_room_path(@location, @room), class: "btn btn-primary btn-sm float-right" %>
    </div>
  </div>
</div>